### ISSUE TITLE
parquet-tools is not a command

### ISSUE THREAD

**Issue by IgorBerman** [yuj/sublime-parquet#1]
Can you provide some info regarding how you have configured it in your PATH? in reality one should use something like "java -jar path-to-parquet-tools.jar ...". On the other hand your code executes parquet-tools as some kind of executable. I've added bash script parquet-tools which has inside something like:
#!/bin/bash
java -jar path-to-parquet-tools-1.6.0.jar "$@"
but I'm still getting error of PATH

**Comment by yuj** [comment]
@IgorBerman Is the script you created in your PATH?  I assume you are on a Linux machine. Could you try to follow the steps described in [@rdblue answer](https://github.com/Parquet/parquet-mr/issues/321) to set up the parquet-tools properly. 

This is what I have on Mac:

> $ cat `which parquet-tools`
#!/bin/bash
exec java  -jar /usr/local/Cellar/parquet-tools/1.8.1/libexec/parquet-tools-1.8.1.jar "$@"

Let me know if you still have problem. Thanks.

**Comment by IgorBerman** [comment]
@yuj yes this helped, thanks a lot!
