### ISSUE TITLE
No Java runtime present, requesting install.

### ISSUE THREAD

**Issue by Kashk** [yuj/sublime-parquet#3]
Hi there,

Thanks for putting this together. I'm trying to get this to work but I get an error that says "No Java runtime present, requesting install."

I've confirmed there is a Java Runtime installed on my mac.

Any ideas what might be happening? 

Thanks again for this package!

-k

**Comment by brentcappello** [comment]
@Kashk Make sure you have the Java8 runtime present. 

`brew cask install java8`

Depending on your build you might need to remove later version of java.

**Comment by yuj** [comment]
Please try the latest version 0.2.1 of the package.  Should work.  It doesn't require Java any more. But Python is required though.
